on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

env:
  TZ: Asia/Tokyo

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 📂 Create generated PDF directory
        run: |
          cp -R ./docs ./dist

      - name: 📝 Generate PDF
        run: |
          npx md-to-pdf ./dist/**/*.md ./dist/*.md

      - name: 🗑 Remove markdown files
        run: |
          rm -rf ./dist/*.md

      - name: 🚀 Push generate files to the repository
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          DATE=$(date +'%Y-%m-%d %H:%M:%S')
          echo '📝 Generate PDF: '$DATE
          git commit -m \"'📝 Generate PDF: '$DATE\"
          git push origin HEAD:${GITHUB_REF}
